# =============================================================================
# ESP32-S3 INTERCOM MINI VA - Voice Assistant + Intercom
# =============================================================================
# Combines voice_assistant + micro_wake_word with intercom_api.
# Uses standard i2s_audio (separate I2S buses: INMP441 mic + MAX98357A speaker).
# Mixer speaker shares hardware speaker between VA and Intercom.
#
# HARDWARE:
#   - Board: ESP32-S3 Mini (4MB Flash, Quad PSRAM)
#   - Microphone: SPH0645 I2S MEMS (I2S_NUM_0) - has DC offset
#   - Speaker: MAX98357A I2S amplifier (I2S_NUM_1)
#   - LED: WS2812 RGB (GPIO21)
#
# GPIO PINOUT:
#   Microphone (SPH0645):   WS=GPIO3, SCK=GPIO2, SD=GPIO4
#   Speaker (MAX98357A):    LRC=GPIO6, BCLK=GPIO7, DIN=GPIO8
#   LED (WS2812):           DATA=GPIO21
# =============================================================================

substitutions:
  name: esp32-s3-mini-va-intercom
  friendly_name: ESP32-S3 Mini VA Intercom

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_LWIP_MAX_SOCKETS: "16"

psram:
  mode: quad
  speed: 80MHz

# =============================================================================
# CONNECTIVITY
# =============================================================================
api:
  on_client_connected:
    - lambda: 'id(intercom).publish_entity_states();'
    - if:
        condition:
          switch.is_off: mute
        then:
          - micro_wake_word.start:
  on_client_disconnected:
    - voice_assistant.stop:

ota:
  - platform: esphome

logger:
  hardware_uart: UART0
  level: DEBUG
  logs:
    intercom_api: INFO
    micro_wake_word: DEBUG

network:
  enable_high_performance: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "s3-mini-va-ic Fallback"

# =============================================================================
# EXTERNAL COMPONENTS
# =============================================================================
external_components:
  - source: esphome/components
    components: [intercom_api, esp_aec]

# =============================================================================
# I2S AUDIO BUSES
# =============================================================================
i2s_audio:
  - id: i2s_mic_bus
    i2s_lrclk_pin: GPIO3
    i2s_bclk_pin: GPIO2
  - id: i2s_spk_bus
    i2s_lrclk_pin: GPIO6
    i2s_bclk_pin: GPIO7

# =============================================================================
# MICROPHONE (SPH0645) - shared by MWW, VA, and Intercom
# =============================================================================
microphone:
  - platform: i2s_audio
    id: mic_component
    i2s_audio_id: i2s_mic_bus
    i2s_din_pin: GPIO4
    adc_type: external
    pdm: false
    bits_per_sample: 32bit
    sample_rate: 16000
    channel: left

# =============================================================================
# SPEAKERS (mixer topology: VA + Intercom -> hw_speaker)
# =============================================================================
speaker:
  - platform: i2s_audio
    id: hw_speaker
    i2s_audio_id: i2s_spk_bus
    i2s_dout_pin: GPIO8
    dac_type: external
    i2s_mode: primary
    sample_rate: 16000
    bits_per_sample: 16bit
    timeout: never
    buffer_duration: 100ms

  - platform: mixer
    id: audio_mixer
    output_speaker: hw_speaker
    num_channels: 1
    source_speakers:
      - id: va_speaker
        timeout: 10s
      - id: intercom_speaker
        timeout: 10s

# =============================================================================
# MEDIA PLAYER (VA TTS output through va_speaker)
# =============================================================================
media_player:
  - platform: speaker
    id: speaker_media_player
    name: "Media Player"
    announcement_pipeline:
      speaker: va_speaker
      format: FLAC
      sample_rate: 16000
      num_channels: 1
    on_announcement:
      - if:
          condition:
            switch.is_off: mute
          then:
            - micro_wake_word.start:
    on_idle:
      - if:
          condition:
            and:
              - not:
                  voice_assistant.is_running:
              - switch.is_off: mute
          then:
            - micro_wake_word.start:

# =============================================================================
# AEC (Acoustic Echo Cancellation)
# =============================================================================
esp_aec:
  id: aec_processor
  sample_rate: 16000
  filter_length: 8
  mode: voip_high_perf

# =============================================================================
# WAKE WORD + VOICE ASSISTANT
# =============================================================================
micro_wake_word:
  id: mww
  microphone: mic_component
  on_wake_word_detected:
    # Barge-in: if TTS is playing, interrupt it and restart VA
    - if:
        condition:
          media_player.is_announcing:
        then:
          - media_player.stop:
              announcement: true
          - voice_assistant.stop:
          - delay: 100ms
    - voice_assistant.start:
        wake_word: !lambda return wake_word;
    - light.turn_on:
        id: status_led
        red: 30%
        green: 30%
        blue: 70%
        brightness: 60%
        effect: "Fast Pulse"
  models:
    - model: "wakewords/hey_trowyayoh.json"

voice_assistant:
  id: va
  microphone: mic_component
  media_player: speaker_media_player
  micro_wake_word: mww
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  on_listening:
    - light.turn_on:
        id: status_led
        brightness: 70%
        red: 0%
        green: 100%
        blue: 0%
        effect: "Slow Pulse"
  on_stt_vad_end:
    - light.turn_on:
        id: status_led
        brightness: 70%
        red: 100%
        green: 55%
        blue: 0%
        effect: "Fast Pulse"
  on_tts_start:
    - light.turn_on:
        id: status_led
        brightness: 100%
        red: 0%
        green: 0%
        blue: 100%
        effect: none
  on_end:
    - wait_until:
        condition:
          - media_player.is_announcing:
        timeout: 0.5s
    - wait_until:
        - and:
            - not:
                media_player.is_announcing:
            - not:
                speaker.is_playing:
                    id: va_speaker
    - delay: 100ms
    - voice_assistant.stop:
    - if:
        condition:
          switch.is_off: mute
        then:
          - micro_wake_word.start:
    - light.turn_off: status_led
    # If intercom call is active, restore streaming LED
    - if:
        condition:
          not:
            intercom_api.is_idle:
              id: intercom
        then:
          - light.turn_on:
              id: status_led
              effect: none
              red: 0%
              green: 100%
              blue: 0%
  on_error:
    - light.turn_on:
        id: status_led
        brightness: 70%
        red: 100%
        green: 0%
        blue: 0%
    - delay: 1s
    - light.turn_off: status_led
    - if:
        condition:
          switch.is_off: mute
        then:
          - micro_wake_word.start:

# =============================================================================
# INTERCOM API (TCP-based, port 6054)
# =============================================================================
intercom_api:
  id: intercom
  mode: full
  microphone: mic_component
  speaker: intercom_speaker
  dc_offset_removal: true
  aec_id: aec_processor
  ringing_timeout: 30s

  on_outgoing_call:
    - light.turn_on:
        id: status_led
        effect: "Ringing"
        red: 100%
        green: 50%
        blue: 0%
    - if:
        condition:
          lambda: 'return id(intercom).get_current_destination() == "Home Assistant";'
        then:
          - homeassistant.event:
              event: esphome.intercom_call
              data:
                caller: !lambda 'return App.get_friendly_name();'
                destination: "Home Assistant"
                type: "doorbell"

  on_ringing:
    - light.turn_on:
        id: status_led
        effect: "Ringing"
        red: 100%
        green: 0%
        blue: 0%

  on_answered:
    - logger.log: "Call answered"

  on_streaming:
    - light.turn_on:
        id: status_led
        effect: none
        red: 0%
        green: 100%
        blue: 0%

  on_idle:
    - light.turn_off: status_led

  on_hangup:
    - logger.log:
        format: "Hangup: %s"
        args: ['reason.c_str()']

  on_call_failed:
    - logger.log:
        format: "Call failed: %s"
        args: ['reason.c_str()']

# =============================================================================
# BUTTONS
# =============================================================================
button:
  - platform: template
    id: call_button
    name: "Call"
    icon: "mdi:phone"
    on_press:
      - intercom_api.call_toggle:
          id: intercom

  - platform: template
    id: next_contact_button
    name: "Next Contact"
    icon: "mdi:arrow-right"
    on_press:
      - intercom_api.next_contact:
          id: intercom

  - platform: template
    id: prev_contact_button
    name: "Previous Contact"
    icon: "mdi:arrow-left"
    on_press:
      - intercom_api.prev_contact:
          id: intercom

  - platform: template
    id: decline_button
    name: "Decline"
    icon: "mdi:phone-hangup"
    on_press:
      - intercom_api.decline_call:
          id: intercom

  - platform: template
    id: refresh_contacts_button
    name: "Refresh Contacts"
    icon: "mdi:refresh"
    entity_category: config
    on_press:
      - intercom_api.set_contacts:
          id: intercom
          contacts_csv: !lambda 'return id(ha_active_devices).state;'

  - platform: restart
    name: "Restart"
    icon: "mdi:restart"

# =============================================================================
# SWITCHES
# =============================================================================
switch:
  - platform: intercom_api
    intercom_api_id: intercom
    auto_answer:
      id: auto_answer_switch
      name: "Auto Answer"
      restore_mode: RESTORE_DEFAULT_ON
    aec:
      id: aec_switch
      name: "Echo Cancellation"
      restore_mode: RESTORE_DEFAULT_OFF

  - platform: template
    id: mute
    name: "Mute"
    icon: "mdi:microphone-off"
    optimistic: true
    on_turn_on:
      - micro_wake_word.stop:
      - voice_assistant.stop:
      - microphone.mute:
          id: mic_component
      - light.turn_on:
          id: status_led
          red: 100%
          green: 0%
          blue: 0%
          brightness: 60%
          effect: "Fast Pulse"
      - delay: 2s
      - light.turn_on:
          id: status_led
          red: 100%
          green: 0%
          blue: 0%
          brightness: 30%
          effect: none
    on_turn_off:
      - microphone.unmute:
          id: mic_component
      - micro_wake_word.start:
      - light.turn_on:
          id: status_led
          red: 0%
          green: 100%
          blue: 0%
          brightness: 60%
          effect: "Fast Pulse"
      - delay: 2s
      - light.turn_off: status_led

# =============================================================================
# NUMBERS
# =============================================================================
number:
  - platform: intercom_api
    intercom_api_id: intercom
    speaker_volume:
      id: speaker_volume
      name: "Speaker Volume"
    mic_gain:
      id: mic_gain
      name: "Mic Gain"

# =============================================================================
# STATUS LED (WS2812 RGB on GPIO21)
# =============================================================================
light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: "Status LED"
    icon: "mdi:led-on"
    pin: GPIO21
    chipset: WS2812
    num_leds: 1
    rgb_order: RGB
    effects:
      - pulse:
          name: "Slow Pulse"
          min_brightness: 20%
          max_brightness: 100%
          transition_length: 1s
          update_interval: 1s
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - strobe:
          name: "Ringing"
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 250ms
            - state: false
              duration: 250ms

# =============================================================================
# TEXT SENSORS
# =============================================================================
text_sensor:
  - platform: homeassistant
    id: ha_active_devices
    entity_id: sensor.intercom_active_devices
    on_value:
      - intercom_api.set_contacts:
          id: intercom
          contacts_csv: !lambda 'return x;'

# =============================================================================
# DIAGNOSTICS
# =============================================================================
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    update_interval: 60s

  - platform: internal_temperature
    name: "CPU Temperature"
    update_interval: 60s
