# ==============================================================================
# ESP32-S3 INTERCOM MINI - New TCP-based API
# ==============================================================================
#
# Uses the new intercom_api component with TCP streaming on port 6054.
# Replaces UDP-based intercom_audio with a more reliable TCP approach.
#
# HARDWARE:
#   - Board: ESP32-S3 Mini (4MB Flash, Quad PSRAM)
#   - Microphone: SPH0645 I2S MEMS (I2S_NUM_0) - has DC offset
#   - Speaker: MAX98357A I2S amplifier (I2S_NUM_1)
#   - LED: WS2812 RGB (GPIO21)
#
# GPIO PINOUT:
#   Microphone (SPH0645):
#     - WS/LRCLK: GPIO3
#     - SCK/BCLK: GPIO2
#     - SD/DIN:   GPIO4
#
#   Speaker (MAX98357A):
#     - LRC/LRCLK: GPIO6
#     - BCLK:      GPIO7
#     - DIN:       GPIO8
#
#   LED (WS2812):
#     - DATA: GPIO21
#
# ==============================================================================

substitutions:
  name: intercom-mini
  friendly_name: Intercom Mini

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: 600
    then:
      - lambda: |-
          // Restore speaker volume from saved state
          float vol = id(speaker_volume).state / 100.0f;
          id(intercom).set_volume(vol);
          // Restore mic gain from saved state (dB)
          id(intercom).set_mic_gain_db(id(mic_gain).state);

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: quad
  speed: 80MHz

# ==============================================================================
# CONNECTIVITY
# ==============================================================================
api:

ota:
  - platform: esphome

logger:
  hardware_uart: UART0
  level: INFO
  logs:
    intercom_api: INFO
    component: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.1.18
  ap:
    ssid: "${name} Fallback"

# ==============================================================================
# EXTERNAL COMPONENTS
# ==============================================================================
external_components:
  - source:
      type: local
      path: esphome_components
    components: [intercom_api, esp_aec]

# ==============================================================================
# I2S AUDIO BUSES
# ==============================================================================
i2s_audio:
  # I2S Bus 0: SPH0645 Microphone
  - id: i2s_mic_bus
    i2s_lrclk_pin: GPIO3
    i2s_bclk_pin: GPIO2

  # I2S Bus 1: MAX98357A Speaker
  - id: i2s_spk_bus
    i2s_lrclk_pin: GPIO6
    i2s_bclk_pin: GPIO7

# ==============================================================================
# MICROPHONE (SPH0645)
# ==============================================================================
microphone:
  - platform: i2s_audio
    id: mic_component
    i2s_audio_id: i2s_mic_bus
    i2s_din_pin: GPIO4
    adc_type: external
    pdm: false
    bits_per_sample: 32bit
    sample_rate: 16000
    channel: left

# ==============================================================================
# SPEAKER (MAX98357A)
# ==============================================================================
speaker:
  - platform: i2s_audio
    id: spk_component
    i2s_audio_id: i2s_spk_bus
    i2s_dout_pin: GPIO8
    dac_type: external
    i2s_mode: primary
    sample_rate: 16000
    bits_per_sample: 16bit
    timeout: never
    buffer_duration: 100ms  # ~6 chunks buffer - low latency without underrun

# ==============================================================================
# AEC (Acoustic Echo Cancellation) - ESP-SR
# ==============================================================================
esp_aec:
  id: aec_processor
  sample_rate: 16000
  filter_length: 4          # 4 recommended for ESP32-S3
  mode: voip_low_cost       # Best for voice intercom

# ==============================================================================
# INTERCOM API (TCP-based, port 6054)
# ==============================================================================
intercom_api:
  id: intercom
  microphone: mic_component
  speaker: spk_component
  mic_bits: 32              # SPH0645 is 32-bit I2S mic
  dc_offset_removal: true   # Required for SPH0645 (has DC bias)
  aec_id: aec_processor     # Link to AEC component

# ==============================================================================
# VOLUME & GAIN CONTROL
# ==============================================================================
number:
  - platform: template
    id: speaker_volume
    name: "Speaker Volume"
    icon: "mdi:volume-high"
    min_value: 0
    max_value: 100
    step: 5
    initial_value: 80
    optimistic: true
    restore_value: true
    unit_of_measurement: "%"
    set_action:
      - lambda: |-
          float vol = x / 100.0f;
          id(intercom).set_volume(vol);

  - platform: template
    id: mic_gain
    name: "Mic Gain"
    icon: "mdi:microphone"
    min_value: -20
    max_value: 20
    step: 1
    initial_value: 0
    optimistic: true
    restore_value: true
    unit_of_measurement: "dB"
    set_action:
      - lambda: |-
          id(intercom).set_mic_gain_db(x);

# ==============================================================================
# SWITCHES
# ==============================================================================
switch:
  - platform: template
    id: aec_switch
    name: "Echo Cancellation"
    icon: "mdi:ear-hearing"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: 'id(intercom).set_aec_enabled(true);'
    turn_off_action:
      - lambda: 'id(intercom).set_aec_enabled(false);'

  - platform: template
    id: auto_answer_switch
    name: "Auto Answer"
    icon: "mdi:phone-incoming"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - lambda: 'id(intercom).set_auto_answer(true);'
    turn_off_action:
      - lambda: 'id(intercom).set_auto_answer(false);'

# ==============================================================================
# STATUS LED (WS2812 RGB on GPIO21)
# ==============================================================================
light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: "Status LED"
    icon: "mdi:led-on"
    pin: GPIO21
    chipset: WS2812
    num_leds: 1
    rgb_order: RGB
    effects:
      - pulse:
          name: "Streaming"
          min_brightness: 20%
          max_brightness: 100%
      - strobe:
          name: "Ringing"
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 250ms
            - state: false
              duration: 250ms

# ==============================================================================
# TEXT SENSORS (status)
# ==============================================================================
text_sensor:
  - platform: intercom_api
    id: intercom_state
    name: "Intercom State"
    intercom_api_id: intercom
    on_value:
      then:
        - if:
            condition:
              text_sensor.state:
                id: intercom_state
                state: "Ringing"
            then:
              - light.turn_on:
                  id: status_led
                  effect: "Ringing"
                  red: 100%
                  green: 0%
                  blue: 0%
        - if:
            condition:
              text_sensor.state:
                id: intercom_state
                state: "Streaming"
            then:
              - light.turn_on:
                  id: status_led
                  effect: "None"
                  red: 0%
                  green: 100%
                  blue: 0%
        - if:
            condition:
              text_sensor.state:
                id: intercom_state
                state: "Idle"
            then:
              - light.turn_off:
                  id: status_led

# ==============================================================================
# DIAGNOSTICS
# ==============================================================================
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    update_interval: 60s

  - platform: internal_temperature
    name: "CPU Temperature"
    update_interval: 60s

button:
  # Call/Answer/Hangup button (P2P mode - calls Home Assistant)
  - platform: template
    id: call_button
    name: "Call"
    icon: "mdi:phone"
    on_press:
      - lambda: |-
          std::string state = id(intercom_state).state;

          // If ringing (incoming call), answer it
          if (state == "Ringing") {
            id(intercom).answer_call();
            return;
          }

          // If in call or streaming, hang up
          if (state == "Streaming" || state == "Calling") {
            id(intercom).stop();
            return;
          }

          // IDLE: Start call to Home Assistant
          id(intercom).start();

  - platform: restart
    name: "Restart"
    icon: "mdi:restart"
